name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest coverage
      - name: Lint
        run: |
          black --check app
          isort --check app
          flake8 app
      - name: Test
        run: |
          pytest --maxfail=1 --disable-warnings
          coverage run -m pytest
          coverage report
